Rework existing ci file
doctrine/deprecations pull request #61
Opened 2023-06-03 10:34 UTC by greg0ire

2023-06-03 10:36 UTC, greg0ire commented
Depending on the outcome of https://github.com/doctrine/deprecations/pull/59, I will add `test_fixtures` to the cs job as well.

2023-06-05 22:09 UTC, SenseException requested changes

2023-06-05 22:09 UTC, SenseException commented on .github/workflows/coding-standards.yml
> +      - src/**
```suggestion
      - lib/**
```

2023-06-05 22:09 UTC, SenseException commented on .github/workflows/coding-standards.yml
> +      - src/**
```suggestion
      - lib/**
```

2023-06-05 22:09 UTC, SenseException commented on .github/workflows/continuous-integration.yml
> +      - src/**
```suggestion
      - lib/**
```

2023-06-05 22:09 UTC, SenseException commented on .github/workflows/continuous-integration.yml
> +      - src/**
```suggestion
      - lib/**
```

2023-06-06 08:58 UTC, greg0ire commented
@SenseException nice catch!

2023-06-07 08:01 UTC, derrabus approved these changes

2023-06-07 19:57 UTC, merged